{% set name = "sagemaker-headless-execution-driver" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sagemaker-headless-execution-driver-{{ version }}.tar.gz
  sha256: 8dc241a7017a0d539dbdc9038e5a553fe451f8cbd9bcd3bfa192b776a6d9d6fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - papermill >=2.4

test:
  imports:
    - sagemaker_headless_execution_driver
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker
  summary: Execution Driver for Notebook Scheduler
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - oztoprakmustafa
